//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotEntities : DbContext
    {
        public hotEntities()
            : base("name=hotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<race> races { get; set; }
        public virtual DbSet<test_table> test_table { get; set; }
        public virtual DbSet<unitcatalogue> unitcatalogues { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<newsfeed> newsfeeds { get; set; }
        public virtual DbSet<unitvault> unitvaults { get; set; }
        public virtual DbSet<mapmetadata> mapmetadatas { get; set; }
    }
}
