//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class race
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int Attack { get; set; }
        public int Dodge { get; set; }
        public int Accuracy { get; set; }
        public int HitPoints { get; set; }
        public int Magic { get; set; }
        public int MovementSpeed { get; set; }
        public int FireResistance { get; set; }
        public int MagicResistance { get; set; }
        public int SlashResistance { get; set; }
        public int PiercingResistance { get; set; }
        public int BludgeoningResistance { get; set; }
        public int ID { get; set; }
    }
}
