//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitvault
    {
        public int ID { get; set; }
        public string Attack { get; set; }
        public string Accuracy { get; set; }
        public string Dodge { get; set; }
        public string HitPoints { get; set; }
        public string Magic { get; set; }
        public string MagicResistance { get; set; }
        public string FireResistance { get; set; }
        public string SlashResistance { get; set; }
        public string PiercingResistance { get; set; }
        public string BludgeoningResistance { get; set; }
        public string MovementSpeed { get; set; }
        public string MinAttRange { get; set; }
        public string MaxAttRange { get; set; }
        public int Experience { get; set; }
        public int Level { get; set; }
        public string Abilities { get; set; }
        public string Owner { get; set; }
        public string CatalogueID { get; set; }
    }
}
