//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitcatalogue
    {
        public int CatalogueID { get; set; }
        public string Name { get; set; }
        public string UnitType { get; set; }
        public string Faction { get; set; }
        public string Rarity { get; set; }
        public string Collection { get; set; }
        public string Race { get; set; }
        public string DamageType { get; set; }
        public string Attack { get; set; }
        public int Accuracy { get; set; }
        public int Dodge { get; set; }
        public int HitPoints { get; set; }
        public string MovementSpeed { get; set; }
        public int Magic { get; set; }
        public int MagicResistance { get; set; }
        public int FireResistance { get; set; }
        public int SlashResistance { get; set; }
        public int PiercingResistance { get; set; }
        public int BludgeoningResistance { get; set; }
        public string MinAttackRange { get; set; }
        public string MaxAttackRange { get; set; }
        public string Abilities { get; set; }
        public string Artist { get; set; }
        public string FlavourText { get; set; }
    }
}
