//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int iId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Gold { get; set; }
        public int Dust { get; set; }
        public int Rank { get; set; }
        public string Deck1 { get; set; }
        public string Deck2 { get; set; }
        public string Deck3 { get; set; }
        public string Deck4 { get; set; }
        public string Deck5 { get; set; }
        public string Deck6 { get; set; }
        public string Deck7 { get; set; }
        public string Deck8 { get; set; }
        public string Deck0 { get; set; }
    }
}
